config/routes.rb
Rails.application.routes.draw do
  get 'clear_cart' => 'sales#clear_cart', as: 'delete_cart'
  resources :sales
  resources :artists
  get '/admin' => 'items#new'

  get '/main' => 'static_pages#main'

  get '/signin' => 'home#index'

  get '/items/date/:date' => 'home#date_search'

  get '/items/style/:style' => 'home#style_search'

  get '/items/medium/:medium' => 'home#medium_search'

  get '/items/size/:size' => 'home#size_search'

  get '/appraisals' => 'static_pages#main'

  post '/sales/add_cart/:id' => 'sales#add_cart', as: 'cart'

  patch 'items/:id/condition-upgrade' => 'items#upgrade', as: :item_upgrade

  patch 'items/:id/condition-downgrade' => 'items#downgrade', as: :item_downgrade



  resources :appraisals
  resources :items
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#main'
end

app/models/appraisal.rb
class Appraisal < ApplicationRecord
  enum condition: [:Mint, :Good, :Average, :Damaged]
  belongs_to :item
  validates :condition, presence: true
  validates :value, presence: true, numericality: { greater_than: 0 }
end

app/controllers/appraisals_controller.rb
class AppraisalsController < ApplicationController
  before_action :set_appraisal, only: [:show, :edit, :update, :destroy]
  before_action :login_check

  # GET /appraisals
  # GET /appraisals.json
  def index
    @appraisals = Appraisal.all
  end

  # GET /appraisals/1
  # GET /appraisals/1.json
  def show
  end

  # GET /appraisals/new
  def new
    @appraisal = Appraisal.new
  end

  # GET /appraisals/1/edit
  def edit
  end

  # POST /appraisals
  # POST /appraisals.json
  def create
    params[:appraisal][:condition] = params[:appraisal][:condition].to_i
    @appraisal = Appraisal.new(appraisal_params)

    respond_to do |format|
      if @appraisal.save
        format.html { redirect_to @appraisal.item }
        format.json { render :show, status: :created, location: @appraisal }
      else
        format.html { render :new }
        format.json { render json: @appraisal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appraisals/1
  # PATCH/PUT /appraisals/1.json
  def update
    params[:appraisal][:condition] = params[:appraisal][:condition].to_i
        respond_to do |format|
      if @appraisal.update_attributes(appraisal_params)
        format.html { redirect_to @appraisal.item }
        format.json { render :show, status: :ok, location: @appraisal }
      else
        format.html { render :edit }
        format.json { render json: @appraisal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appraisals/1
  # DELETE /appraisals/1.json
  def destroy
    @appraisal.destroy
    respond_to do |format|
      format.html { redirect_to appraisals_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appraisal
      @appraisal = Appraisal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def appraisal_params
      params.require(:appraisal).permit(:id, :item_id, :previous_owner, :value, :condition)
    end

    def login_check
      if user_signed_in?

      else
        redirect_to signin_path
      end
    end
end

app/helpers/appraisals_helper.rb
module AppraisalsHelper
end

app/views/appraisals/_form.html.erb
<%= form_with(model: appraisal, local: true) do |form| %>
  <% if appraisal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(appraisal.errors.count, "error") %> prohibited this appraisal from being saved:</h2>

      <ul>
      <% appraisal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %><br />

  <!-- <div class="field">
    <%# form.label :id %>
    <%# form.number_field :id, id: :appraisal_id %>
  </div> -->

  <!-- <div class="field">
    <%# form.label :item_id %>
    <%# form.number_field :item_id, id: :appraisal_item_id %>
  </div> -->
  <div class="field">
    <%= form.label :Picture_Title %><br />
    <%= form.select :item_id, options_for_select( Item.all.map{|t| [t.title, t.id]}), id: :appraisal_item_id %>
  </div><br />

  <div class="field">
    <%= form.label :Previous_Owner %><br />
    <%= form.text_field :previous_owner, id: :appraisal_previous_owner %>
  </div><br />

  <div class="field">
    <%= form.label :Value %><br />
    <%= form.number_field :value, id: :appraisal_value %>
  </div><br />

  <div class="field">
    <%= form.label :Condition %><br />
    <%= form.radio_button(:condition, 0) %>
    <%= label_tag(:condition, "Mint") %>
    <%= form.radio_button(:condition, 1) %>
    <%= label_tag(:condition, "Good") %>
    <%= form.radio_button(:condition, 2) %>
    <%= label_tag(:condition, "Average") %>
    <%= form.radio_button(:condition, 3) %>
    <%= label_tag(:condition, "Damaged") %>
  </div><br />

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/appraisals/edit.html.erb
<div id="editAppraisalDiv">
	<h1>Editing Appraisal</h1>
		<%= render 'form', appraisal: @appraisal %>
		<!-- <%# link_to 'Back To Picture Page', item_path@item, method: :get %> -->
</div>

app/views/appraisals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Appraisals</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Item</th>
      <th>Previous owner</th>
      <th>Value</th>
      <th>Condition</th>
      <th>Item</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @appraisals.each do |appraisal| %>
      <tr>
        <td><%= appraisal.id %></td>
        <td><%= appraisal.item_id %></td>
        <td><%= appraisal.previous_owner %></td>
        <td><%= appraisal.value %></td>
        <td><%= appraisal.condition %></td>
        <td><%= appraisal.item %></td>
        <td><%= link_to 'Show', appraisal %></td>
        <td><%= link_to 'Edit', edit_appraisal_path(appraisal) %></td>
        <td><%= link_to 'Destroy', appraisal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Appraisal', new_appraisal_path %>

app/views/appraisals/new.html.erb
<div id="newAppraisalDiv">
	<h1>New Appraisal</h1>
		<%= render 'form', appraisal: @appraisal %>
		<!-- <%# link_to 'Back to Picture', @item %> -->
</div>

app/views/appraisals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @appraisal.id %>
</p>

<p>
  <strong>Item:</strong>
  <%= @appraisal.item_id %>
</p>

<p>
  <strong>Previous owner:</strong>
  <%= @appraisal.previous_owner %>
</p>

<p>
  <strong>Value:</strong>
  <%= @appraisal.value %>
</p>

<p>
  <strong>Condition:</strong>
  <%= @appraisal.condition %>
</p>

<p>
  <strong>Item:</strong>
  <%= @appraisal.item %>
</p>

<%= link_to 'Edit', edit_appraisal_path(@appraisal) %> |
<%= link_to 'Back', appraisals_path %>