config/routes.rb
Rails.application.routes.draw do
  get 'clear_cart' => 'sales#clear_cart', as: 'delete_cart'
  resources :sales
  resources :artists
  get '/admin' => 'items#new'

  get '/main' => 'static_pages#main'

  get '/signin' => 'home#index'

  get '/items/date/:date' => 'home#date_search'

  get '/items/style/:style' => 'home#style_search'

  get '/items/medium/:medium' => 'home#medium_search'

  get '/items/size/:size' => 'home#size_search'

  get '/appraisals' => 'static_pages#main'

  post '/sales/add_cart/:id' => 'sales#add_cart', as: 'cart'

  patch 'items/:id/condition-upgrade' => 'items#upgrade', as: :item_upgrade

  patch 'items/:id/condition-downgrade' => 'items#downgrade', as: :item_downgrade



  resources :appraisals
  resources :items
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#main'
end

app/models/item.rb
class Item < ApplicationRecord
  enum size: [:Small, :Medium, :Large]
  enum status: [:Available, :Leased]
  belongs_to :artist
  has_many :appraisals
  has_many :sale_items
  has_attached_file :picture, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\z/
  validates :status, presence: true, numericality: { in: 0..1 }
  validates :size, presence: true, numericality: { in: 0..2 }
  validates :yoc, presence: true, numericality: { greater_than: 0 }
  validates :medium, presence: true, format: /\A[-a-z]+\z/i
  validates :style , presence: true, format: /\A[-a-z]+\z/i
  validates :origin_country , presence: true, format: /\A[-a-z\W]+\z/i  
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy, :upgrade, :downgrade]
  before_action :login_check, except: [:index]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # upgrade the item condition
  def upgrade
    # to do: cap at max status
    @item.status = (Item.statuses[@item.status]||0) + 1
    respond_to do |format|
      if @item.save
        format.json { render :show, status: :ok, location: @item }
      else
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # downgrade the item condition
  def downgrade
    # to do: cap at min status
    @item.status = (Item.statuses[@item.status]||0) - 1
    respond_to do |format|
      if @item.save
        format.json { render :show, status: :ok, location: @item }
      else
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:id, :artist_id, :title, :medium, :style, :size, :yoc, :origin_country, :picture)
    end

    def login_check
      if user_signed_in?

      else
        redirect_to signin_path
      end
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_with(model: item, local: true, html: {multipart: true}) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <!-- <div class="field">
    <%# form.label :id %>
    <%# form.number_field :id, id: :item_id %>
  </div> -->

  <div class="field">
    <%= form.text_field :title, id: :item_title, placeholder: 'Title' %>
  </div>

  <div class="field">
    <%= form.label :Artist %><br />
    <%= form.select :artist_id, options_for_select( Artist.all.map{|a| [a.full_name, a.id]}), id: :item_artist_id %>
  </div>

  <div class="field">
    <%= form.label :Medium %><br />
    <%= form.select :medium, options_for_select( Item.all.map{|m| [m.medium]}) %>
  </div>

  <div class="field">
    <%= form.label :Style %><br />
    <%= form.select :style, options_for_select( Item.all.map{|s| [s.style]}) %>
  </div>

  <!-- <div class="field">
    <%# form.number_field :size, id: :item_size, placeholder: 'Size' %>
  </div> -->

  <div class="field">
    <%= form.label :Size %><br />
    <%= radio_button_tag(:size, 0) %>
    <%= label_tag(:size, "Small: <36in") %><br />
    <%= radio_button_tag(:age, 1) %>
    <%= label_tag(:size, "Medium: 36-72in") %><br />
    <%= radio_button_tag(:age, 2) %>
    <%= label_tag(:size, "Large: >72in") %>
  </div>

  <!-- <div class="field">
    <%# form.number_field :status, id: :item_status, placeholder: 'Status (available or leased)' %>
  </div> -->

  <div class="field">
    <%= form.number_field :yoc, id: :item_yoc, :max => 2017, placeholder: 'Year of Creation' %>
  </div>

  <div class="field">
    <%= form.text_field :origin_country, id: :item_origin_country, placeholder: 'Country of Origin' %>
  </div>

  <div class="field">
    <%= form.label :picture %>
    <%= form.file_field :picture %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<div id="editItemDiv">
	<h1>Editing Item</h1>
		<%= render 'form', item: @item %>
		<%= link_to 'Back To Picture Page', @item %> |  
		<%= link_to 'Delete Item', item_path(@item), method: :delete %>
</div>

app/views/items/index.html.erb
<!-- Browse -->
<div id="gallery">
<ul>
  <% @items.each do |item| %>
    <a href="/items/<%= item.id %>">
      <li class="galleryPic" style="background-image:url(<%= Item.find(item.id).picture %>)">
      <span class="galleryPicTitle"><%= item.title %></span><br />
      <span class="galleryPicArtist"><%= item.artist.full_name %></span></li>
    </a>
  <% end %>
</ul>
</div>

app/views/items/new.html.erb
<div id="newItemDiv">
	<h1>Add New Picture</h1>
		<%= render 'form', item: @item %>
		<%= link_to 'Back To Browse', items_path %>
</div>

app/views/items/show.html.erb
<div id="picturePage">

<div id="itemPicture">
  <p>
    <%= image_tag @item.picture.url %>
  </p>
</div>

<p>
  <strong>Title:</strong><br />
  <%= @item.title %>
</p>

<p>
  <strong>Artist:</strong><br />
  <%= @item.artist.full_name %>
</p>

<p class="moreInfo">
  <strong>Year Of Creation:</strong><br />
  <%= @item.yoc %>
</p>

<p class="moreInfo">
  <strong>Origin Country:</strong><br />
  <%= @item.origin_country %>
</p>

<p class="moreInfo">
  <strong>Style:</strong><br />
  <%= @item.style %>
</p>

<p class="moreInfo">
  <strong>Medium:</strong><br />
  <%= @item.medium %>
</p>

<p class="moreInfo">
  <strong>Status:</strong><br />
  <%= link_to "- ", item_downgrade_path(@item), method: :patch, remote: true, class: "artwork-status-change" if current_user && current_user.admin == true %><span class="artwork-status"><%= @item.status %></span> <%= link_to "+", item_upgrade_path(@item), method: :patch, remote: true, class: "artwork-status-change" if current_user && current_user.admin == true %>
</p>

<p class="moreInfo">
  <strong>Size:</strong><br />
  <%= @item.size %>
</p>

<button id="moreInfoButton" class="hideInfoButton" type="button">More Info</button><br /><br />

<button id="appraisalButton" type="button" onclick="showAppModal()">See Last Appraisal</button><br /><br />

<div id="modalBody">
  <div id="appraisalModal">
    <% if @item.appraisals.any? %>
      Previous Owner: <%= @item.appraisals.last.previous_owner %>
      <br>
      Value: $<%= @item.appraisals.last.value %>
      <br>
      Condition: <%= @item.appraisals.last.condition %>
      <br>
      <%= link_to "Edit Appraisal", edit_appraisal_path if current_user && current_user.admin == true %>
    <% else %>
      <p>Item does not have an appraisal right now.<p><br />
      <%= link_to "Add Appraisal", new_appraisal_path if current_user && current_user.admin == true %>
      <br>
    <% end %>
    <br>
    <button type="button" onclick="closeAppModal()">Close</button>
  </div>
</div>

<!-- add to cart if available: -->
<% if @item.status == "Available" %>
  <%= link_to 'Add to Cart', cart_path(@item), method: :post %>  |
<% else %>
  <h4>Sorry, this item is currently on lease.</h4>
<% end %>
<!-- edit picture if user is an admin: -->
<% if current_user && current_user.admin == true %>
  <%= link_to 'Edit', edit_item_path(@item) %> |
  <%= link_to 'Back To Gallery', items_path %>
<% else %>
  <%= link_to 'Back To Gallery', items_path %>
<% end %>
</div>