config/routes.rb
Rails.application.routes.draw do
  get 'clear_cart' => 'sales#clear_cart', as: 'delete_cart'
  resources :sales
  resources :artists
  get '/admin' => 'items#new'

  get '/main' => 'static_pages#main'

  get '/signin' => 'home#index'

  get '/items/date/:date' => 'home#date_search'

  get '/items/style/:style' => 'home#style_search'

  get '/items/medium/:medium' => 'home#medium_search'

  get '/items/size/:size' => 'home#size_search'

  get '/appraisals' => 'static_pages#main'

  post '/sales/add_cart/:id' => 'sales#add_cart', as: 'cart'

  patch 'items/:id/condition-upgrade' => 'items#upgrade', as: :item_upgrade

  patch 'items/:id/condition-downgrade' => 'items#downgrade', as: :item_downgrade



  resources :appraisals
  resources :items
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#main'
end

app/models/sale.rb
class Sale < ApplicationRecord
  belongs_to :user
  has_many :sale_items
  has_many :items, through: :sale_items
  validates :phone_number, presence: true, format: /\A\(?(\d{3})\)?[- ]?(\d{3})[- ]?(\d{4})\z/
  validates :lease_duration, presence: true, numericality: { greater_than: 0 }
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: [:show, :edit, :update, :destroy]
  before_action :login_check

  # GET /sales
  # GET /sales.json
  def index
    @sales = Sale.all
  end

  # GET /sales/1
  # GET /sales/1.json
  def show
  end

  # GET /sales/new
  def new
    @sale = Sale.new
  end

  # GET /sales/1/edit
  def edit
  end

  # POST /sales
  # POST /sales.json
  def create
    Sale.transaction do
      @sale = Sale.create(sale_params)
      session[:cart].each do |item_id|
        SaleItem.create(sale_id: @sale.id, item_id: item_id)
        item = Item.find(item_id)
        item.status = 1
        item.save
      end if session[:cart]
    end
    session[:cart] = nil if @sale.id
    respond_to do |format|
      if @sale.id
        format.html { redirect_to @sale, notice: 'Sale was successfully created.' }
        format.json { render :show, status: :created, location: @sale }
      else
        format.html { render :new }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1
  # PATCH/PUT /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to @sale, notice: 'Sale was successfully updated.' }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_url, notice: 'Sale was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def add_cart
    if session[:cart].nil?
      session[:cart] = [params[:id]]
    else
      session[:cart].push(params[:id])
      session[:cart].uniq!
    end
    redirect_back(fallback_location: root_path)
  end

  def clear_cart
    session[:cart].clear
    redirect_back(fallback_location: root_path)
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_params
      params.require(:sale).permit(:user_id, :address, :payment_amount, :lease_duration, :item_id, :phone_number)
    end

    def login_check
      if user_signed_in?

      else
        redirect_to signin_path
      end
    end
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/_edit.html.erb
<!-- <h2>Edit <%# resource_name.to_s.humanize %></h2> -->

<%= form_for(resource, as: resource_name, url: registration_path(resource_name), html: { method: :put }) do |f| %>
  <%= devise_error_messages! %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true %>
  </div>

  <% if devise_mapping.confirmable? && resource.pending_reconfirmation? %>
    <div>Currently waiting confirmation for: <%= resource.unconfirmed_email %></div>
  <% end %>

  <div class="field">
    <%= f.label :password %> <br /><i>(leave blank if you don't want to change it)</i><br />
    <%= f.password_field :password, autocomplete: "off" %>
    <% if @minimum_password_length %>
      <br />
      <em><%= @minimum_password_length %> characters minimum</em>
    <% end %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "off" %>
  </div>

  <div class="field">
    <%= f.label :current_password %> <br /><i>(we need your current password to confirm your changes)</i><br />
    <%= f.password_field :current_password, autocomplete: "off" %>
  </div>

  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>
<br />
<h3>Cancel My Account</h3>

<p><%= button_to "Delete Account", registration_path(resource_name), data: { confirm: "Are you sure?" }, method: :delete %></p>

app/views/sales/_form.html.erb
<%= form_with(model: sale, local: true) do |form| %>
  <% if sale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sale.errors.count, "error") %> prohibited this sale from being saved:</h2>

      <ul>
      <% sale.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_field :address, id: :sale_address, placeholder: 'City' %>
  </div>

  <div class="field">
    <%= form.number_field :lease_duration, id: :sale_lease_duration, placeholder: 'Lease Duration (Months)' %>
  </div>

  <div class="field">
    <%= form.text_field :phone_number, id: :sale_phone_number, placeholder: 'Valid 10 Digit Phone Number' %>
  </div>

  <div class="field">
    <%= form.hidden_field :user_id, id: :sale_user_id %>
  </div>

  <div class="field">
    <%= form.hidden_field :payment_amount, id: :sale_payment_amount %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sales/edit.html.erb
<h1>Editing Sale</h1>

<%= render 'form', sale: @sale %>

<%= link_to 'Show', @sale %> |
<%= link_to 'Back', sales_path %>

app/views/sales/index.html.erb
<div id="accountPage">
	<h1><%= current_user.full_name if current_user %></h1>
		<button id="editUserButton" class="hideEditButton" type="button">Edit Account Info</button><br />
			<div id="editUserDiv" class="hiddenForm">
				<h1>Edit Account Info</h1>
				<%= render 'edit' %>
			</div>
</div>
<div id="saleIndexDiv">
	<h1>Previously Leased Items</h1>
		<% @sales.each do |sale| %>
    		<% sale.items.each do |item| %>
					<% if current_user && current_user.id == sale.user_id %>
					<ul>
					<a href="/items/<%= item.id %>">
      					<li class="galleryPic" style="background-image:url(<%= Item.find(item.id).picture %>)">
      					<span class="galleryPicTitle"><%= item.title %></span><br />
      					<span class="galleryPicArtist"><%= item.artist.full_name %></span></li>
   					</a>
   					</ul>
						<br>
					<% end %>
    		<% end %>
		<% end %>
</div>

app/views/sales/new.html.erb
<div id="newSaleDiv">
	<h1>Complete Your Purchase</h1>
		<h3>In Cart:</h3>
		<div id="cartDiv">
		<% if (session[:cart]||[]).length > 0 %>
			<% session[:cart].each do |id| %>
				<% ids = id.to_i %>
				<span class="saleThumbs">
      					<li class="salePic" style="background-image:url(<%= Item.find(ids).picture %>)">
      					<span class="salePicTitle"><%= Item.find(ids).title %></span><br />
      					<span class="salePicArtist"><%= Item.find(ids).artist.full_name %></span></li>

   				</span>
				<%# Item.find(ids).title %>
				<br>
			<% end %>
			<span id="clearCartSpan">
			<%= link_to "Clear Cart", delete_cart_path %></span><br /><br />
		</div>
			<h3>Your Purchasing Info:</h3>
			<%= render 'form', sale: Sale.new(user_id: current_user.id) %>
		<% else %>
			<br /><h4>Add some items to your cart!</h4>
		<% end %>
</div>

app/views/sales/show.html.erb
<div id="saleShowDiv">
  <p id="notice"><%= notice %></p>

  <p>
    <strong>User:</strong>
    <%= @sale.user.full_name %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= @sale.address %>
  </p>

 <!--  <p>
    <strong>Payment amount:</strong>
    <%# @sale.payment_amount %>
  </p> -->

  <p>
    <strong>Lease duration:</strong>
    <%= @sale.lease_duration %> Months
  </p>

  <p>Thank you for shopping with us!</p>

  <%= link_to 'Account Page', '/sales' %>
</div>